# Generated by Django 5.2 on 2025-05-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_documental', '0005_departamento_remove_usuario_cedula_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciadocumento',
            name='departamento_origen',
            field=models.CharField(choices=[('Ventas', 'Ventas'), ('Legal', 'Legal'), ('Administrativo', 'Administrativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transferenciadocumento',
            name='departamento_destino',
            field=models.CharField(choices=[('Ventas', 'Ventas'), ('Legal', 'Legal'), ('Administrativo', 'Administrativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(choices=[('Ventas', 'Ventas'), ('Legal', 'Legal'), ('Administrativo', 'Administrativo')], default='Ventas', max_length=20),
        ),
        migrations.RemoveField(
            model_name='rol',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
