# Generated by Django 5.2 on 2025-05-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_documental', '0006_alter_transferenciadocumento_departamento_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
