# Generated by Django 5.2 on 2025-05-28 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_documental', '0007_usuario_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=255)),
                ('identification', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='historialchat',
            name='carpeta',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='carpeta',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='usuario_subidor',
        ),
        migrations.RemoveField(
            model_name='transferenciadocumento',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='historialchat',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='historialchat',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='mensajechat',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='transferenciadocumento',
            name='usuario_responsable',
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('role', models.CharField(max_length=50)),
                ('ai_tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_documental.aitutorial')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('log', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_documental.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department_name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_documental.organization')),
            ],
        ),
        migrations.CreateModel(
            name='StorageOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_storage', models.FloatField()),
                ('storage_used', models.FloatField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_documental.organization')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_documental.organization')),
            ],
        ),
        migrations.CreateModel(
            name='QuickAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_folder', models.CharField(max_length=100)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_documental.user')),
            ],
        ),
        migrations.AddField(
            model_name='aitutorial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_documental.user'),
        ),
        migrations.CreateModel(
            name='UsersDepartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_documental.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_documental.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Carpeta',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='HistorialChat',
        ),
        migrations.DeleteModel(
            name='MensajeChat',
        ),
        migrations.DeleteModel(
            name='TransferenciaDocumento',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
