# Generated by Django 5.2 on 2025-05-30 04:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_documental', '0008_aitutorial_organization_remove_historialchat_carpeta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.TextField()),
                ('file_type', models.TextField(blank=True, null=True)),
                ('file_size', models.FloatField()),
                ('url', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='app_gestion_documental.storageorganization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_archives', to='app_gestion_documental.user')),
            ],
        ),
    ]
